// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schmersal_Models.Sch_Entities;

namespace Schmersal_Models.Migrations
{
    [DbContext(typeof(Sch_Context))]
    [Migration("20211124164517_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schmersal_Models.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Company_Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Controlling_Id")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Created_By")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Customer_Id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("DateTime");

                    b.Property<string>("Erp_Project_Id")
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset>("Modified_At")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Modified_By")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Project_Name")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Staff_Id")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("DateTime");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tenant_Id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblProject");
                });
#pragma warning restore 612, 618
        }
    }
}
